require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DataCollectorsController do

  def mock_data_collector(stubs={})
    @mock_data_collector ||= mock_model(DataCollector, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all data_collectors as @data_collectors" do
      DataCollector.stub(:all) { [mock_data_collector] }
      get :index
      assigns(:data_collectors).should eq([mock_data_collector])
    end
  end

  describe "GET show" do
    it "assigns the requested data_collector as @data_collector" do
      DataCollector.stub(:find).with("37") { mock_data_collector }
      get :show, :id => "37"
      assigns(:data_collector).should be(mock_data_collector)
    end
  end

  describe "GET new" do
    it "assigns a new data_collector as @data_collector" do
      DataCollector.stub(:new) { mock_data_collector }
      get :new
      assigns(:data_collector).should be(mock_data_collector)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_collector as @data_collector" do
      DataCollector.stub(:find).with("37") { mock_data_collector }
      get :edit, :id => "37"
      assigns(:data_collector).should be(mock_data_collector)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created data_collector as @data_collector" do
        DataCollector.stub(:new).with({'these' => 'params'}) { mock_data_collector(:save => true) }
        post :create, :data_collector => {'these' => 'params'}
        assigns(:data_collector).should be(mock_data_collector)
      end

      it "redirects to the created data_collector" do
        DataCollector.stub(:new) { mock_data_collector(:save => true) }
        post :create, :data_collector => {}
        response.should redirect_to(data_collector_url(mock_data_collector))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_collector as @data_collector" do
        DataCollector.stub(:new).with({'these' => 'params'}) { mock_data_collector(:save => false) }
        post :create, :data_collector => {'these' => 'params'}
        assigns(:data_collector).should be(mock_data_collector)
      end

      it "re-renders the 'new' template" do
        DataCollector.stub(:new) { mock_data_collector(:save => false) }
        post :create, :data_collector => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_collector" do
        DataCollector.stub(:find).with("37") { mock_data_collector }
        mock_data_collector.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :data_collector => {'these' => 'params'}
      end

      it "assigns the requested data_collector as @data_collector" do
        DataCollector.stub(:find) { mock_data_collector(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:data_collector).should be(mock_data_collector)
      end

      it "redirects to the data_collector" do
        DataCollector.stub(:find) { mock_data_collector(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(data_collector_url(mock_data_collector))
      end
    end

    describe "with invalid params" do
      it "assigns the data_collector as @data_collector" do
        DataCollector.stub(:find) { mock_data_collector(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:data_collector).should be(mock_data_collector)
      end

      it "re-renders the 'edit' template" do
        DataCollector.stub(:find) { mock_data_collector(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_collector" do
      DataCollector.stub(:find).with("37") { mock_data_collector }
      mock_data_collector.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the data_collectors list" do
      DataCollector.stub(:find) { mock_data_collector }
      delete :destroy, :id => "1"
      response.should redirect_to(data_collectors_url)
    end
  end

end
