require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ScriptTargetsController do

  def mock_script_target(stubs={})
    @mock_script_target ||= mock_model(ScriptTarget, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all script_targets as @script_targets" do
      ScriptTarget.stub(:all) { [mock_script_target] }
      get :index
      assigns(:script_targets).should eq([mock_script_target])
    end
  end

  describe "GET show" do
    it "assigns the requested script_target as @script_target" do
      ScriptTarget.stub(:find).with("37") { mock_script_target }
      get :show, :id => "37"
      assigns(:script_target).should be(mock_script_target)
    end
  end

  describe "GET new" do
    it "assigns a new script_target as @script_target" do
      ScriptTarget.stub(:new) { mock_script_target }
      get :new
      assigns(:script_target).should be(mock_script_target)
    end
  end

  describe "GET edit" do
    it "assigns the requested script_target as @script_target" do
      ScriptTarget.stub(:find).with("37") { mock_script_target }
      get :edit, :id => "37"
      assigns(:script_target).should be(mock_script_target)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created script_target as @script_target" do
        ScriptTarget.stub(:new).with({'these' => 'params'}) { mock_script_target(:save => true) }
        post :create, :script_target => {'these' => 'params'}
        assigns(:script_target).should be(mock_script_target)
      end

      it "redirects to the created script_target" do
        ScriptTarget.stub(:new) { mock_script_target(:save => true) }
        post :create, :script_target => {}
        response.should redirect_to(script_target_url(mock_script_target))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved script_target as @script_target" do
        ScriptTarget.stub(:new).with({'these' => 'params'}) { mock_script_target(:save => false) }
        post :create, :script_target => {'these' => 'params'}
        assigns(:script_target).should be(mock_script_target)
      end

      it "re-renders the 'new' template" do
        ScriptTarget.stub(:new) { mock_script_target(:save => false) }
        post :create, :script_target => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested script_target" do
        ScriptTarget.stub(:find).with("37") { mock_script_target }
        mock_script_target.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :script_target => {'these' => 'params'}
      end

      it "assigns the requested script_target as @script_target" do
        ScriptTarget.stub(:find) { mock_script_target(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:script_target).should be(mock_script_target)
      end

      it "redirects to the script_target" do
        ScriptTarget.stub(:find) { mock_script_target(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(script_target_url(mock_script_target))
      end
    end

    describe "with invalid params" do
      it "assigns the script_target as @script_target" do
        ScriptTarget.stub(:find) { mock_script_target(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:script_target).should be(mock_script_target)
      end

      it "re-renders the 'edit' template" do
        ScriptTarget.stub(:find) { mock_script_target(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested script_target" do
      ScriptTarget.stub(:find).with("37") { mock_script_target }
      mock_script_target.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the script_targets list" do
      ScriptTarget.stub(:find) { mock_script_target }
      delete :destroy, :id => "1"
      response.should redirect_to(script_targets_url)
    end
  end

end
